/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Source Sans 3',
          '"Inter"',
          'sohne',
          '"Helvetica Neue"',
          'Helvetica',
          'Arial',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'sans-serif',
        ],
        serif: [
          '"Source Serif 4"',
          '"Source Serif Pro"',
          'Charter',
          'Georgia',
          'Cambria',
          '"Times New Roman"',
          'Times',
          'serif',
        ],
        mono: [
          'JetBrains Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
        display: ['"Source Sans 3"', '"Inter"', 'sohne', 'sans-serif'],
      },
      colors: {
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        ink: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            fontFamily:
              '"Source Serif 4", "Source Serif Pro", Charter, Georgia, Cambria, "Times New Roman", Times, serif',
            fontSize: '1.25rem',
            lineHeight: '1.6',
            letterSpacing: '-0.003em',
            color: 'rgb(36 36 36)',
            '--tw-prose-body': 'rgb(36 36 36)',
            '--tw-prose-headings': 'rgb(36 36 36)',
            '--tw-prose-lead': 'rgb(36 36 36)',
            '--tw-prose-links': 'rgb(36 36 36)',
            '--tw-prose-bold': 'rgb(36 36 36)',
            '--tw-prose-counters': 'rgb(117 117 117)',
            '--tw-prose-bullets': 'rgb(117 117 117)',
            '--tw-prose-hr': '#e6e6e6',
            '--tw-prose-quotes': 'rgb(36 36 36)',
            '--tw-prose-quote-borders': '#e6e6e6',
            '--tw-prose-captions': 'rgb(117 117 117)',
            '--tw-prose-code': 'rgb(36 36 36)',
            '--tw-prose-pre-code': '#e6e6e6',
            '--tw-prose-pre-bg': 'rgb(15 23 42 / 0.95)',
            '--tw-prose-th-borders': '#e6e6e6',
            '--tw-prose-td-borders': '#e6e6e6',
            h1: {
              fontFamily:
                '"Source Sans 3", "Inter", sohne, "Helvetica Neue", Helvetica, Arial, ui-sans-serif, system-ui, sans-serif',
              fontWeight: '700',
              fontSize: '2.625rem',
              lineHeight: '1.24',
              letterSpacing: '-0.011em',
              marginTop: '0',
              marginBottom: '0.5em',
            },
            h2: {
              fontFamily:
                '"Source Sans 3", "Inter", sohne, "Helvetica Neue", Helvetica, Arial, ui-sans-serif, system-ui, sans-serif',
              fontWeight: '700',
              fontSize: '1.875rem',
              lineHeight: '1.27',
              letterSpacing: '-0.014em',
              marginTop: '2em',
              marginBottom: '0.5em',
            },
            h3: {
              fontFamily:
                '"Source Sans 3", "Inter", sohne, "Helvetica Neue", Helvetica, Arial, ui-sans-serif, system-ui, sans-serif',
              fontWeight: '600',
              fontSize: '1.5rem',
              lineHeight: '1.33',
              letterSpacing: '-0.012em',
              marginTop: '1.6em',
              marginBottom: '0.4em',
            },
            h4: {
              fontFamily:
                '"Source Sans 3", "Inter", sohne, "Helvetica Neue", Helvetica, Arial, ui-sans-serif, system-ui, sans-serif',
              fontWeight: '600',
              fontSize: '1.125rem',
              lineHeight: '1.4',
              marginTop: '1.4em',
              marginBottom: '0.4em',
            },
            p: {
              marginTop: '0',
              marginBottom: '1.6em',
            },
            a: {
              textDecoration: 'underline',
              textDecorationThickness: '1px',
              textUnderlineOffset: '2px',
              textDecorationColor: 'rgba(36,36,36,0.4)',
              fontWeight: 'inherit',
            },
            'a:hover': {
              textDecorationColor: 'rgb(36 36 36)',
            },
            strong: {
              fontWeight: '600',
            },
            blockquote: {
              fontStyle: 'italic',
              borderLeftWidth: '3px',
              paddingLeft: '1.25em',
              color: 'rgb(36 36 36)',
            },
            'blockquote p:first-of-type::before': { content: 'none' },
            'blockquote p:last-of-type::after': { content: 'none' },
            figcaption: {
              fontFamily:
                '"Source Sans 3", "Inter", sohne, "Helvetica Neue", Helvetica, Arial, ui-sans-serif, system-ui, sans-serif',
              fontSize: '0.875rem',
              color: 'rgb(117 117 117)',
              marginTop: '0.75em',
              textAlign: 'center',
            },
            'figure img': {
              marginTop: '2em',
              marginBottom: '0.5em',
              borderRadius: '4px',
            },
            'ul > li::marker': {
              color: 'rgb(117 117 117)',
            },
            'ol > li::marker': {
              color: 'rgb(117 117 117)',
              fontVariantNumeric: 'tabular-nums',
            },
            hr: {
              marginTop: '3em',
              marginBottom: '3em',
              borderColor: '#e6e6e6',
            },
            code: {
              fontFamily:
                'JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
              fontWeight: '500',
              fontSize: '0.9em',
              backgroundColor: '#f2f2f2',
              padding: '0.15em 0.35em',
              borderRadius: '3px',
            },
            'code::before': { content: 'none' },
            'code::after': { content: 'none' },
          },
        },
        invert: {
          css: {
            fontFamily:
              '"Source Serif 4", "Source Serif Pro", Charter, Georgia, Cambria, "Times New Roman", Times, serif',
            fontSize: '1.25rem',
            lineHeight: '1.6',
            letterSpacing: '-0.003em',
            color: 'rgb(230 230 230)',
            '--tw-prose-body': 'rgb(230 230 230)',
            '--tw-prose-headings': 'rgb(255 255 255)',
            '--tw-prose-lead': 'rgb(230 230 230)',
            '--tw-prose-links': 'rgb(255 255 255)',
            '--tw-prose-bold': 'rgb(255 255 255)',
            '--tw-prose-counters': 'rgb(160 160 160)',
            '--tw-prose-bullets': 'rgb(160 160 160)',
            '--tw-prose-hr': 'rgb(60 60 60)',
            '--tw-prose-quotes': 'rgb(230 230 230)',
            '--tw-prose-quote-borders': 'rgb(80 80 80)',
            '--tw-prose-captions': 'rgb(160 160 160)',
            '--tw-prose-code': 'rgb(255 211 130)',
            '--tw-prose-pre-code': 'rgb(230 230 230)',
            '--tw-prose-pre-bg': 'rgb(15 23 42 / 0.95)',
            '--tw-prose-th-borders': 'rgb(80 80 80)',
            '--tw-prose-td-borders': 'rgb(60 60 60)',
            a: {
              textDecorationColor: 'rgba(255,255,255,0.35)',
            },
            'a:hover': {
              textDecorationColor: 'rgb(255 255 255)',
            },
            code: {
              backgroundColor: 'rgb(40 40 40)',
              color: 'rgb(255 211 130)',
            },
          },
        },
      }),
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out both',
        'fade-up': 'fadeUp 0.6s ease-out both',
        shimmer: 'shimmer 2.4s linear infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
